apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: cluster-administrator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "get", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-role-binding
subjects: #(user details)
- kind: User
  name: cluster-admin 
  apiGroup: rbac.authorization.k8s.io
roleRef: #(details about the clusterRole)
  kind: ClusterRole
  name: cluster-administrator
  apiGroup: rbac.authorization.k8s.io