apiVersion: apps/v1
kind: Deployment
metadata: 
     name: my-deployment
     labels:
      app: myapp
      type: front-end
spec:
  replicas: 3
  selector: 
    matchLabels:
        type: front-end
  template:
    metadata: 
      name: myapp-pod
      labels: 
          app:  myapp
          type: front-end
    spec: 
      containers: 
      - name: myapp-container
        image: myapp
