# Example Kubeconfig file @ ~/.kube/config:

apiVersion: v1
kind: Config 
current-context: dev-user@google    #(will use this as the default context)
clusters:    #(in array format)
  - name: my-kube-playground
    cluster: 
      certificate-authority: ca.crt (/etc/kubernetes/pki/ca.crt)
      server: https://my-kube-playground:6443 #(server address)
  - name: development
  - name: prod
  - name: google
contexts:
  - name: my-kube-admin@my-kube-playground
    context:
      cluster: my-kube-playground
      user: my-kube-admin
  - name: dev-user@google
  - name: prod-user@prod
users:
  - name: my-kube-admin
    user:
      client-certificate: admin.crt #(/etc/kubernetes/pki/users/admin.crt)
      client-key: admin.key #(/etc/kubernetes/pki/users/admin.key)
  - name: admin 
  - name: dev-user
  - name: prod-user