apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: #limit
      cpu: 500m 
    defaultRequest:  #request
      cpu: 500m
    max: #maximum limit that can be set on a container in a pod
      cpu: "1" #(example values)
    min: # minimum request a pod can make
      cpu: 100m
    type: Container

