apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: data-processor
    image: data-processor
  nodeSelector: # pod must have been labeled prior to using this NodeSelector
    size: Large
