apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod#(string)
  namespace: dev # This makes sure that the pod gets created in the "dev" namespace
  labels:
    app: myapp
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx