apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-developer-binding
subjects: #(where we specify user details)
- kind: User 
  name: dev-user 
  apiGroup: rbac.authorization.k8s.io
roleRef: #(where we provide the details of the role we created)
  kind: Role 
  name: developer 
  apiGroup: rbac.authorization.k8s.io